/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectkelompok;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author rubyi
 */
public class FormTanggapan extends javax.swing.JFrame {
    
      public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.koneksi();
    


    /**
     * Creates new form FormPetugas
     */
public FormTanggapan() {
    initComponents();
    tanggal.setSelectedItem(new Date()); // Inisialisasi dengan tanggal hari ini
    btnSubmit = new JButton("Submit");
    judul();
    tampilData("");
    tabModel = new DefaultTableModel();
    getDataFromDatabase(); // Initialize tabModel here
}

private void getDataFromDatabase() {
    try {
        st = cn.createStatement();
        ResultSet resultSet = st.executeQuery("SELECT tgl_pengaduan FROM pengaduan WHERE nama = 'hirzi'");

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        while (resultSet.next()) {
            Date date = resultSet.getDate("tgl_pengaduan");
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateString = dateFormat.format(date);
            comboBoxModel.addElement(dateString);
        }

        // Set model data to JComboBox
        tanggal.setModel(comboBoxModel);

        resultSet.close();
        st.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}




    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_petugas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tanggapan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTanggapan = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        judul_laporan = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tanggal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setText("TANGGAPAN");

        jLabel1.setText("ID PETUGAS");

        jLabel2.setText("JUDUL LAPORAN");

        jLabel3.setText("TANGGAPAN");

        jLabel4.setText("TANGGAL PENGADUAN");

        tanggapan.setColumns(20);
        tanggapan.setRows(5);
        jScrollPane2.setViewportView(tanggapan);

        tableTanggapan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Petugas", "Judul Laporan", "Tanggal", "Tanggapan"
            }
        ));
        tableTanggapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTanggapanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTanggapan);

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Dashboard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUbah))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_petugas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul_laporan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(judul_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnCancel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnUbah)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTanggapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTanggapanMouseClicked
        id_petugas.setText(tableTanggapan.getValueAt(tableTanggapan.getSelectedRow(), 0).toString());
        judul_laporan.setText(tableTanggapan.getValueAt(tableTanggapan.getSelectedRow(), 1).toString());

        // Mengonversi nilai tanggal dari String ke java.util.Date
        try {
            String tanggalString = tableTanggapan.getValueAt(tableTanggapan.getSelectedRow(), 2).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Sesuaikan dengan format tanggal di tabel
            Date tanggalDate = dateFormat.parse(tanggalString);
            
            // Ubah nilai pada JComboBox
            tanggal.setSelectedItem(tanggalDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        tanggapan.setText(tableTanggapan.getValueAt(tableTanggapan.getSelectedRow(), 3).toString());
        btnSubmit.setEnabled(false);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        id_petugas.setEnabled(false);
    
    }//GEN-LAST:event_tableTanggapanMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
   try {
    st = cn.createStatement();
    String idPetugas = id_petugas.getText();
    String judulLaporan = judul_laporan.getText();
    String isiTanggapan = tanggapan.getText();

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String selectedDateString = (String) tanggal.getSelectedItem();

    if (selectedDateString != null) {
        try {
            Date selectedDate = dateFormat.parse(selectedDateString);

            String formattedDate = dateFormat.format(selectedDate);

            String query = "INSERT INTO tanggapan (id_petugas, judul_laporan, tanggal, tanggapan) VALUES ('" + idPetugas + "', '"
                    + judulLaporan + "', '" + formattedDate + "', '" + isiTanggapan + "')";

            st.executeUpdate(query);
            tampilData("");
            JOptionPane.showMessageDialog(null, "Simpan Berhasil");
            reset();
        } catch (ParseException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error parsing date. Please select a valid date.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih tanggal terlebih dahulu.");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
 try {
    st = cn.createStatement();
    String idPetugas = id_petugas.getText();
    String judulLaporan = judul_laporan.getText();
    String isiTanggapan = tanggapan.getText();

    // Menggunakan SimpleDateFormat untuk mengonversi tanggal menjadi format yang sesuai
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String selectedDate = (String) tanggal.getSelectedItem(); // Mengambil tanggal dari JComboBox sebagai String

    if (selectedDate != null) {
        String query = "UPDATE tanggapan SET judul_laporan = '" + judulLaporan + "', "
                + "tanggal = '" + selectedDate + "', tanggapan = '" + isiTanggapan + "' WHERE id_petugas = '" + idPetugas + "'";

        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null, "Update Berhasil");

        DefaultTableModel model = (DefaultTableModel) tableTanggapan.getModel();
        int selectedRow = tableTanggapan.getSelectedRow();
        if (selectedRow != -1) {
            model.setValueAt(judulLaporan, selectedRow, 1);
            model.setValueAt(selectedDate, selectedRow, 2);
            model.setValueAt(isiTanggapan, selectedRow, 3);
        }

        reset();
    } else {
        JOptionPane.showMessageDialog(null, "Pilih tanggal terlebih dahulu.");
    }
} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         reset();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
        int jawab;

        if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin Menghapus Data?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            st = cn.createStatement();

            int selectedRow = tableTanggapan.getSelectedRow();
            if (selectedRow >= 0) {
                String idPetugas = tabModel.getValueAt(selectedRow, 0).toString();
                st.executeUpdate("DELETE FROM tanggapan WHERE id_petugas='" + idPetugas + "'");
                tampilData("");
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus terlebih dahulu.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Dahboard fl= new Dahboard();
        fl.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FormLogin fl= new FormLogin();
        fl.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTanggapan().setVisible(true);
            }
        });
    }
    public void judul() {
    Object[] judul = {
        "ID PETUGAS", "JUDUL LAPORAN", "TANGGAL PENGADUAN", "TANGGAPAN"
    };
    tabModel = new DefaultTableModel(null, judul);
    tableTanggapan.setModel(tabModel);
}

  public void tampilData(String where) {
    try {
        st = cn.createStatement();
        tabModel.getDataVector().removeAllElements();
        tabModel.fireTableDataChanged();
        
        // Pastikan query SQL yang benar dengan WHERE clause
        String query = "SELECT * FROM tanggapan " + where;
        
        rs = st.executeQuery(query);
        
        while (rs.next()) {
            Object[] data = {
                rs.getString("id_petugas"),
                rs.getString("judul_laporan"),
                rs.getString("tanggal"),
                rs.getString("tanggapan")
            };
            tabModel.addRow(data);
        }
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try {
            // Pastikan Anda menutup statement dan result set setelah digunakan
            if (rs != null) {
                rs.close();
            }
            if (st != null) {
                st.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}

    public void reset() {
        id_petugas.setText("");
        judul_laporan.setText("");
        tanggal.setSelectedItem(null);
        tanggapan.setText("");
        btnSubmit.setEnabled(true);
        id_petugas.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField id_petugas;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField judul_laporan;
    private javax.swing.JTable tableTanggapan;
    private javax.swing.JComboBox<String> tanggal;
    private javax.swing.JTextArea tanggapan;
    // End of variables declaration//GEN-END:variables
}
